CREATE DATABASE react_php;
USE react_php;

CREATE TABLE IF NOT EXISTS user
(
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  CONSTRAINT user_email_uindex UNIQUE (email)
);
