controllers:
    default_controller:
        service: 'default_controller'
        actions:
            - { method: 'GET', route: '/', action: 'hello' }

    user_controller:
        service: 'user_controller'
        actions:
            - { method: 'GET', route: '/users', action: 'getAll' }
            - { method: 'POST', route: '/user', action: 'createUser' }
            - { method: 'GET', route: '/user/{id}', action: 'getUser' }
            - { method: 'PUT', route: '/user/{id}', action: 'updateUser' }
